/*
 * This file is generated by jOOQ.
 */
package keywhiz.jooq.tables;


import java.util.Arrays;
import java.util.List;

import keywhiz.jooq.Indexes;
import keywhiz.jooq.Keys;
import keywhiz.jooq.KeywhizdbTest;
import keywhiz.jooq.tables.records.AccessgrantsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accessgrants extends TableImpl<AccessgrantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>keywhizdb_test.accessgrants</code>
     */
    public static final Accessgrants ACCESSGRANTS = new Accessgrants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccessgrantsRecord> getRecordType() {
        return AccessgrantsRecord.class;
    }

    /**
     * The column <code>keywhizdb_test.accessgrants.id</code>.
     */
    public final TableField<AccessgrantsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>keywhizdb_test.accessgrants.groupid</code>.
     */
    public final TableField<AccessgrantsRecord, Long> GROUPID = createField(DSL.name("groupid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>keywhizdb_test.accessgrants.secretid</code>.
     */
    public final TableField<AccessgrantsRecord, Long> SECRETID = createField(DSL.name("secretid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>keywhizdb_test.accessgrants.updatedat</code>.
     */
    public final TableField<AccessgrantsRecord, Long> UPDATEDAT = createField(DSL.name("updatedat"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>keywhizdb_test.accessgrants.createdat</code>.
     */
    public final TableField<AccessgrantsRecord, Long> CREATEDAT = createField(DSL.name("createdat"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>keywhizdb_test.accessgrants.row_hmac</code>.
     */
    public final TableField<AccessgrantsRecord, String> ROW_HMAC = createField(DSL.name("row_hmac"), SQLDataType.VARCHAR(64).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    private Accessgrants(Name alias, Table<AccessgrantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Accessgrants(Name alias, Table<AccessgrantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>keywhizdb_test.accessgrants</code> table
     * reference
     */
    public Accessgrants(String alias) {
        this(DSL.name(alias), ACCESSGRANTS);
    }

    /**
     * Create an aliased <code>keywhizdb_test.accessgrants</code> table
     * reference
     */
    public Accessgrants(Name alias) {
        this(alias, ACCESSGRANTS);
    }

    /**
     * Create a <code>keywhizdb_test.accessgrants</code> table reference
     */
    public Accessgrants() {
        this(DSL.name("accessgrants"), null);
    }

    public <O extends Record> Accessgrants(Table<O> child, ForeignKey<O, AccessgrantsRecord> key) {
        super(child, key, ACCESSGRANTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : KeywhizdbTest.KEYWHIZDB_TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACCESSGRANTS_ACCESSGRANTS_SECRETID_IDX);
    }

    @Override
    public Identity<AccessgrantsRecord, Long> getIdentity() {
        return (Identity<AccessgrantsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccessgrantsRecord> getPrimaryKey() {
        return Keys.KEY_ACCESSGRANTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<AccessgrantsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACCESSGRANTS_ACCESSGRANTS_GROUPID_SECRETID_IDX);
    }

    @Override
    public Accessgrants as(String alias) {
        return new Accessgrants(DSL.name(alias), this);
    }

    @Override
    public Accessgrants as(Name alias) {
        return new Accessgrants(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Accessgrants rename(String name) {
        return new Accessgrants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Accessgrants rename(Name name) {
        return new Accessgrants(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
