/*
 * This file is generated by jOOQ.
 */
package keywhiz.jooq.tables.records;


import keywhiz.jooq.tables.Accessgrants;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessgrantsRecord extends UpdatableRecordImpl<AccessgrantsRecord> implements Record6<Long, Long, Long, Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>keywhizdb_test.accessgrants.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>keywhizdb_test.accessgrants.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>keywhizdb_test.accessgrants.groupid</code>.
     */
    public void setGroupid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>keywhizdb_test.accessgrants.groupid</code>.
     */
    public Long getGroupid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>keywhizdb_test.accessgrants.secretid</code>.
     */
    public void setSecretid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>keywhizdb_test.accessgrants.secretid</code>.
     */
    public Long getSecretid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>keywhizdb_test.accessgrants.updatedat</code>.
     */
    public void setUpdatedat(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>keywhizdb_test.accessgrants.updatedat</code>.
     */
    public Long getUpdatedat() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>keywhizdb_test.accessgrants.createdat</code>.
     */
    public void setCreatedat(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>keywhizdb_test.accessgrants.createdat</code>.
     */
    public Long getCreatedat() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>keywhizdb_test.accessgrants.row_hmac</code>.
     */
    public void setRowHmac(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>keywhizdb_test.accessgrants.row_hmac</code>.
     */
    public String getRowHmac() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Accessgrants.ACCESSGRANTS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Accessgrants.ACCESSGRANTS.GROUPID;
    }

    @Override
    public Field<Long> field3() {
        return Accessgrants.ACCESSGRANTS.SECRETID;
    }

    @Override
    public Field<Long> field4() {
        return Accessgrants.ACCESSGRANTS.UPDATEDAT;
    }

    @Override
    public Field<Long> field5() {
        return Accessgrants.ACCESSGRANTS.CREATEDAT;
    }

    @Override
    public Field<String> field6() {
        return Accessgrants.ACCESSGRANTS.ROW_HMAC;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGroupid();
    }

    @Override
    public Long component3() {
        return getSecretid();
    }

    @Override
    public Long component4() {
        return getUpdatedat();
    }

    @Override
    public Long component5() {
        return getCreatedat();
    }

    @Override
    public String component6() {
        return getRowHmac();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGroupid();
    }

    @Override
    public Long value3() {
        return getSecretid();
    }

    @Override
    public Long value4() {
        return getUpdatedat();
    }

    @Override
    public Long value5() {
        return getCreatedat();
    }

    @Override
    public String value6() {
        return getRowHmac();
    }

    @Override
    public AccessgrantsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public AccessgrantsRecord value2(Long value) {
        setGroupid(value);
        return this;
    }

    @Override
    public AccessgrantsRecord value3(Long value) {
        setSecretid(value);
        return this;
    }

    @Override
    public AccessgrantsRecord value4(Long value) {
        setUpdatedat(value);
        return this;
    }

    @Override
    public AccessgrantsRecord value5(Long value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public AccessgrantsRecord value6(String value) {
        setRowHmac(value);
        return this;
    }

    @Override
    public AccessgrantsRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccessgrantsRecord
     */
    public AccessgrantsRecord() {
        super(Accessgrants.ACCESSGRANTS);
    }

    /**
     * Create a detached, initialised AccessgrantsRecord
     */
    public AccessgrantsRecord(Long id, Long groupid, Long secretid, Long updatedat, Long createdat, String rowHmac) {
        super(Accessgrants.ACCESSGRANTS);

        setId(id);
        setGroupid(groupid);
        setSecretid(secretid);
        setUpdatedat(updatedat);
        setCreatedat(createdat);
        setRowHmac(rowHmac);
    }
}
