/*
 * This file is generated by jOOQ.
 */
package keywhiz.jooq.tables.records;


import keywhiz.jooq.tables.Memberships;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembershipsRecord extends UpdatableRecordImpl<MembershipsRecord> implements Record6<Long, Long, Long, Long, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>keywhizdb_test.memberships.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>keywhizdb_test.memberships.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>keywhizdb_test.memberships.groupid</code>.
     */
    public void setGroupid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>keywhizdb_test.memberships.groupid</code>.
     */
    public Long getGroupid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>keywhizdb_test.memberships.clientid</code>.
     */
    public void setClientid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>keywhizdb_test.memberships.clientid</code>.
     */
    public Long getClientid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>keywhizdb_test.memberships.updatedat</code>.
     */
    public void setUpdatedat(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>keywhizdb_test.memberships.updatedat</code>.
     */
    public Long getUpdatedat() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>keywhizdb_test.memberships.createdat</code>.
     */
    public void setCreatedat(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>keywhizdb_test.memberships.createdat</code>.
     */
    public Long getCreatedat() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>keywhizdb_test.memberships.row_hmac</code>.
     */
    public void setRowHmac(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>keywhizdb_test.memberships.row_hmac</code>.
     */
    public String getRowHmac() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, Long, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, Long, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Memberships.MEMBERSHIPS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Memberships.MEMBERSHIPS.GROUPID;
    }

    @Override
    public Field<Long> field3() {
        return Memberships.MEMBERSHIPS.CLIENTID;
    }

    @Override
    public Field<Long> field4() {
        return Memberships.MEMBERSHIPS.UPDATEDAT;
    }

    @Override
    public Field<Long> field5() {
        return Memberships.MEMBERSHIPS.CREATEDAT;
    }

    @Override
    public Field<String> field6() {
        return Memberships.MEMBERSHIPS.ROW_HMAC;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getGroupid();
    }

    @Override
    public Long component3() {
        return getClientid();
    }

    @Override
    public Long component4() {
        return getUpdatedat();
    }

    @Override
    public Long component5() {
        return getCreatedat();
    }

    @Override
    public String component6() {
        return getRowHmac();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getGroupid();
    }

    @Override
    public Long value3() {
        return getClientid();
    }

    @Override
    public Long value4() {
        return getUpdatedat();
    }

    @Override
    public Long value5() {
        return getCreatedat();
    }

    @Override
    public String value6() {
        return getRowHmac();
    }

    @Override
    public MembershipsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MembershipsRecord value2(Long value) {
        setGroupid(value);
        return this;
    }

    @Override
    public MembershipsRecord value3(Long value) {
        setClientid(value);
        return this;
    }

    @Override
    public MembershipsRecord value4(Long value) {
        setUpdatedat(value);
        return this;
    }

    @Override
    public MembershipsRecord value5(Long value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public MembershipsRecord value6(String value) {
        setRowHmac(value);
        return this;
    }

    @Override
    public MembershipsRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembershipsRecord
     */
    public MembershipsRecord() {
        super(Memberships.MEMBERSHIPS);
    }

    /**
     * Create a detached, initialised MembershipsRecord
     */
    public MembershipsRecord(Long id, Long groupid, Long clientid, Long updatedat, Long createdat, String rowHmac) {
        super(Memberships.MEMBERSHIPS);

        setId(id);
        setGroupid(groupid);
        setClientid(clientid);
        setUpdatedat(updatedat);
        setCreatedat(createdat);
        setRowHmac(rowHmac);
    }
}
