/*
 * This file is generated by jOOQ.
 */
package keywhiz.jooq.tables.records;


import keywhiz.jooq.tables.SecretsContent;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecretsContentRecord extends UpdatableRecordImpl<SecretsContentRecord> implements Record11<Long, Long, Long, Long, String, String, String, String, Long, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>keywhizdb_test.secrets_content.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.secretid</code>.
     */
    public void setSecretid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.secretid</code>.
     */
    public Long getSecretid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.updatedat</code>.
     */
    public void setUpdatedat(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.updatedat</code>.
     */
    public Long getUpdatedat() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.createdat</code>.
     */
    public void setCreatedat(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.createdat</code>.
     */
    public Long getCreatedat() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.createdby</code>.
     */
    public void setCreatedby(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(4);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(5);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.encrypted_content</code>.
     */
    public void setEncryptedContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.encrypted_content</code>.
     */
    public String getEncryptedContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.metadata</code>.
     */
    public void setMetadata(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.metadata</code>.
     */
    public String getMetadata() {
        return (String) get(7);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.expiry</code>.
     */
    public void setExpiry(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.expiry</code>.
     */
    public Long getExpiry() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.content_hmac</code>.
     */
    public void setContentHmac(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.content_hmac</code>.
     */
    public String getContentHmac() {
        return (String) get(9);
    }

    /**
     * Setter for <code>keywhizdb_test.secrets_content.row_hmac</code>.
     */
    public void setRowHmac(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>keywhizdb_test.secrets_content.row_hmac</code>.
     */
    public String getRowHmac() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, Long, Long, String, String, String, String, Long, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, Long, Long, String, String, String, String, Long, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SecretsContent.SECRETS_CONTENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return SecretsContent.SECRETS_CONTENT.SECRETID;
    }

    @Override
    public Field<Long> field3() {
        return SecretsContent.SECRETS_CONTENT.UPDATEDAT;
    }

    @Override
    public Field<Long> field4() {
        return SecretsContent.SECRETS_CONTENT.CREATEDAT;
    }

    @Override
    public Field<String> field5() {
        return SecretsContent.SECRETS_CONTENT.CREATEDBY;
    }

    @Override
    public Field<String> field6() {
        return SecretsContent.SECRETS_CONTENT.UPDATEDBY;
    }

    @Override
    public Field<String> field7() {
        return SecretsContent.SECRETS_CONTENT.ENCRYPTED_CONTENT;
    }

    @Override
    public Field<String> field8() {
        return SecretsContent.SECRETS_CONTENT.METADATA;
    }

    @Override
    public Field<Long> field9() {
        return SecretsContent.SECRETS_CONTENT.EXPIRY;
    }

    @Override
    public Field<String> field10() {
        return SecretsContent.SECRETS_CONTENT.CONTENT_HMAC;
    }

    @Override
    public Field<String> field11() {
        return SecretsContent.SECRETS_CONTENT.ROW_HMAC;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSecretid();
    }

    @Override
    public Long component3() {
        return getUpdatedat();
    }

    @Override
    public Long component4() {
        return getCreatedat();
    }

    @Override
    public String component5() {
        return getCreatedby();
    }

    @Override
    public String component6() {
        return getUpdatedby();
    }

    @Override
    public String component7() {
        return getEncryptedContent();
    }

    @Override
    public String component8() {
        return getMetadata();
    }

    @Override
    public Long component9() {
        return getExpiry();
    }

    @Override
    public String component10() {
        return getContentHmac();
    }

    @Override
    public String component11() {
        return getRowHmac();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSecretid();
    }

    @Override
    public Long value3() {
        return getUpdatedat();
    }

    @Override
    public Long value4() {
        return getCreatedat();
    }

    @Override
    public String value5() {
        return getCreatedby();
    }

    @Override
    public String value6() {
        return getUpdatedby();
    }

    @Override
    public String value7() {
        return getEncryptedContent();
    }

    @Override
    public String value8() {
        return getMetadata();
    }

    @Override
    public Long value9() {
        return getExpiry();
    }

    @Override
    public String value10() {
        return getContentHmac();
    }

    @Override
    public String value11() {
        return getRowHmac();
    }

    @Override
    public SecretsContentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SecretsContentRecord value2(Long value) {
        setSecretid(value);
        return this;
    }

    @Override
    public SecretsContentRecord value3(Long value) {
        setUpdatedat(value);
        return this;
    }

    @Override
    public SecretsContentRecord value4(Long value) {
        setCreatedat(value);
        return this;
    }

    @Override
    public SecretsContentRecord value5(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public SecretsContentRecord value6(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public SecretsContentRecord value7(String value) {
        setEncryptedContent(value);
        return this;
    }

    @Override
    public SecretsContentRecord value8(String value) {
        setMetadata(value);
        return this;
    }

    @Override
    public SecretsContentRecord value9(Long value) {
        setExpiry(value);
        return this;
    }

    @Override
    public SecretsContentRecord value10(String value) {
        setContentHmac(value);
        return this;
    }

    @Override
    public SecretsContentRecord value11(String value) {
        setRowHmac(value);
        return this;
    }

    @Override
    public SecretsContentRecord values(Long value1, Long value2, Long value3, Long value4, String value5, String value6, String value7, String value8, Long value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecretsContentRecord
     */
    public SecretsContentRecord() {
        super(SecretsContent.SECRETS_CONTENT);
    }

    /**
     * Create a detached, initialised SecretsContentRecord
     */
    public SecretsContentRecord(Long id, Long secretid, Long updatedat, Long createdat, String createdby, String updatedby, String encryptedContent, String metadata, Long expiry, String contentHmac, String rowHmac) {
        super(SecretsContent.SECRETS_CONTENT);

        setId(id);
        setSecretid(secretid);
        setUpdatedat(updatedat);
        setCreatedat(createdat);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setEncryptedContent(encryptedContent);
        setMetadata(metadata);
        setExpiry(expiry);
        setContentHmac(contentHmac);
        setRowHmac(rowHmac);
    }
}
