/*
 * This file is generated by jOOQ.
 */
package keywhiz.jooq;


import keywhiz.jooq.tables.Accessgrants;
import keywhiz.jooq.tables.Clients;
import keywhiz.jooq.tables.Groups;
import keywhiz.jooq.tables.Memberships;
import keywhiz.jooq.tables.SchemaVersion;
import keywhiz.jooq.tables.Secrets;
import keywhiz.jooq.tables.SecretsContent;
import keywhiz.jooq.tables.Users;


/**
 * Convenience access to all tables in keywhizdb_test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>keywhizdb_test.accessgrants</code>.
     */
    public static final Accessgrants ACCESSGRANTS = Accessgrants.ACCESSGRANTS;

    /**
     * The table <code>keywhizdb_test.clients</code>.
     */
    public static final Clients CLIENTS = Clients.CLIENTS;

    /**
     * The table <code>keywhizdb_test.groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>keywhizdb_test.memberships</code>.
     */
    public static final Memberships MEMBERSHIPS = Memberships.MEMBERSHIPS;

    /**
     * The table <code>keywhizdb_test.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>keywhizdb_test.secrets</code>.
     */
    public static final Secrets SECRETS = Secrets.SECRETS;

    /**
     * The table <code>keywhizdb_test.secrets_content</code>.
     */
    public static final SecretsContent SECRETS_CONTENT = SecretsContent.SECRETS_CONTENT;

    /**
     * The table <code>keywhizdb_test.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
